# Generated by Django 6.0 on 2025-12-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=200, verbose_name='책 제목')),
                ('bauthor', models.CharField(max_length=100, verbose_name='저자')),
                ('bpublisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('bprice', models.IntegerField(verbose_name='가격')),
                ('bimage', models.URLField(blank=True, null=True, verbose_name='이미지')),
                ('blink', models.URLField(blank=True, null=True, verbose_name='구매 링크')),
                ('bdescription', models.TextField(blank=True, null=True, verbose_name='책 소개')),
                ('bisbn', models.CharField(max_length=50, unique=True, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
