# Generated by Django 6.0 on 2026-01-06 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=2)),
                ('mtype_desc', models.CharField(max_length=100)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(max_length=1000)),
                ('mcontent', models.TextField(blank=True, null=True)),
                ('mthumbnail', models.TextField(blank=True, null=True)),
                ('mfile', models.FileField(blank=True, default='', null=True, upload_to='magazine/')),
                ('mhit', models.IntegerField(default=0)),
                ('mdate', models.DateTimeField(auto_now_add=True)),
                ('magazinecode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.magazinecode')),
            ],
        ),
    ]
