# Generated by Django 6.0 on 2026-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
        ('member', '0002_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='mlike',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_myuser', to='member.myuser'),
        ),
    ]
