# Generated by Django 6.0 on 2025-12-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_bpubdate_alter_book_bprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bhit',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
