# Generated by Django 6.0 on 2026-01-13 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_myuser_is_active_myuser_is_admin'),
        ('restaurants', '0014_restaurantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('rcontent', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('ino', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='review.review')),
            ],
        ),
    ]
