# Generated by Django 6.0 on 2026-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_post_is_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
