# Generated by Django 6.0 on 2025-12-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurants_addr_remove_restaurants_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='addr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='locno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='mem_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='res_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='tel',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='resno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
