# Generated by Django 6.0 on 2026-01-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
