# Generated by Django 6.0 on 2025-12-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='date',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='locno',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='mem_id',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='res_name',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='tel',
        ),
    ]
