# Generated by Django 6.0 on 2025-12-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurants_addr_restaurants_date_restaurants_desc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
