# Generated by Django 6.0 on 2026-01-06 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_myuser_last_login'),
        ('restaurants', '0008_remove_restaurant_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='member',
        ),
        migrations.RemoveField(
            model_name='img',
            name='member',
        ),
        migrations.RemoveField(
            model_name='restaurantopertime',
            name='member',
        ),
        migrations.AddField(
            model_name='comment',
            name='MyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='MyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
        migrations.AddField(
            model_name='img',
            name='MyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
        migrations.AddField(
            model_name='restaurantopertime',
            name='MyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
    ]
