# Generated by Django 6.0 on 2026-01-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_foodmenu_myuser_remove_img_myuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='res_nm',
            new_name='res_name',
        ),
    ]
