# Generated by Django 6.0 on 2026-01-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_rename_res_nm_restaurant_res_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('fcatno', models.AutoField(primary_key=True, serialize=False)),
                ('food_cat', models.CharField(max_length=200, null=True)),
                ('sort', models.IntegerField(default=0)),
            ],
        ),
    ]
