# Generated by Django 6.0 on 2025-12-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
