# Generated by Django 6.0 on 2025-12-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='vote',
        ),
    ]
