# Generated by Django 6.0 on 2026-01-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
        ('member', '0002_myuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=100, unique=True, verbose_name='아이디')),
                ('mpw', models.CharField(max_length=200, verbose_name='비밀번호')),
            ],
        ),
    ]
