# Generated by Django 6.0 on 2026-01-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='mcontent',
            field=models.TextField(null=True),
        ),
    ]
