# Generated by Django 6.0 on 2026-01-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_magazine_mcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='mcontent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='mthumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
