# Generated by Django 6.0 on 2026-01-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_alter_magazine_mcontent_alter_magazine_mthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='mdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='mfile',
            field=models.FileField(blank=True, default='', null=True, upload_to='magazine/'),
        ),
    ]
