# Generated by Django 6.0 on 2026-01-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_comment_member_remove_foodmenu_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='MyUser',
        ),
        migrations.RemoveField(
            model_name='img',
            name='MyUser',
        ),
        migrations.RemoveField(
            model_name='restaurantopertime',
            name='MyUser',
        ),
    ]
