# Generated by Django 6.0 on 2026-01-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0014_restaurantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('kicker', models.CharField(blank=True, default='', max_length=30)),
                ('title', models.CharField(max_length=60)),
                ('sub', models.CharField(blank=True, default='', max_length=80)),
                ('cta_text', models.CharField(blank=True, default='자세히 보기', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
    ]
