# Generated by Django 6.0 on 2026-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
        ('member', '0003_myuser_is_active_myuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=100, unique=True, verbose_name='아이디')),
                ('mpw', models.CharField(max_length=200, verbose_name='비밀번호')),
            ],
        ),
        migrations.AddField(
            model_name='magazine',
            name='mlike',
            field=models.ManyToManyField(blank=True, related_name='like_myuser', to='member.myuser'),
        ),
    ]
