# Generated by Django 6.0 on 2026-01-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_foodmenu_restaurantopertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('ftypeno', models.AutoField(primary_key=True, serialize=False)),
                ('ftype', models.CharField(max_length=50, null=True)),
                ('img_url_main', models.TextField(blank=True, null=True)),
                ('is_main', models.CharField(default='n', max_length=1, null=True)),
                ('sort', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locno', models.AutoField(primary_key=True, serialize=False)),
                ('loc_nm', models.CharField(max_length=50, null=True)),
                ('is_main', models.CharField(default='n', max_length=1, null=True)),
                ('sort', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('locdno', models.AutoField(primary_key=True, serialize=False)),
                ('locd_nm', models.CharField(max_length=50, null=True)),
                ('is_main', models.CharField(max_length=1, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.location')),
            ],
        ),
    ]
