# Generated by Django 6.0 on 2026-01-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_myuser_last_login'),
        ('restaurants', '0006_foodtype_location_locationdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='res_name',
            new_name='res_nm',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='locno',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='mem_id',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='foodType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.foodtype'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.location'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='locationDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.locationdetail'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.location'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='locationDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.locationdetail'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
        migrations.AddField(
            model_name='restaurantopertime',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurantopertime',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantopertime',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.location'),
        ),
        migrations.AddField(
            model_name='restaurantopertime',
            name='locationDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.locationdetail'),
        ),
        migrations.AddField(
            model_name='restaurantopertime',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('ccontent', models.TextField(null=True)),
                ('rating', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.location')),
                ('locationDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.locationdetail')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('imgno', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.TextField(null=True)),
                ('img_nm', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('foodMenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.foodmenu')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.location')),
                ('locationDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.locationdetail')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.myuser')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
    ]
