# Generated by Django 6.0 on 2026-01-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='foodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.foodcategory'),
        ),
    ]
