# Generated by Django 6.0 on 2026-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.CharField(max_length=25, unique=True)),
                ('mem_pw', models.CharField(max_length=200)),
                ('mem_nm', models.CharField(max_length=50)),
                ('nick_nm', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('base_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('food_cat', models.CharField(blank=True, max_length=200, null=True)),
                ('join_path', models.CharField(blank=True, max_length=50, null=True)),
                ('join_path_etc', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
