# Generated by Django 6.0 on 2026-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_options_comment_image_post_is_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
