# Generated by Django 6.0 on 2025-12-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('resno', models.IntegerField(primary_key=True, serialize=False)),
                ('locno', models.IntegerField(default=0)),
                ('res_name', models.CharField(max_length=50)),
                ('desc', models.TextField(null=True)),
                ('addr', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=13)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('mem_id', models.CharField(max_length=25)),
            ],
        ),
    ]
