# Generated by Django 6.0 on 2026-01-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('fnm', models.CharField(max_length=100, null=True)),
                ('resno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOperTime',
            fields=[
                ('opno', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.CharField(max_length=50, null=True)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('resno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
    ]
