# Generated by Django 6.0 on 2026-01-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_res_name_restaurant_res_nm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='member',
        ),
    ]
