# Generated by Django 6.0 on 2026-01-13 07:15

import django.db.models.deletion
import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_foodtype_foodcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('r_img_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=restaurants.models.restaurant_image_path)),
                ('is_main', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('restaurant',), name='uniq_main_image_per_restaurant')],
            },
        ),
    ]
