# Generated by Django 6.0 on 2025-12-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bpubdate',
            field=models.DateField(blank=True, null=True, verbose_name='출판일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='가격'),
        ),
    ]
